<?php
/**
 * PublicApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PublicApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PublicApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for blockFromComment
     *
     * .
     *
     */
    public function testBlockFromComment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for checkedCommentsForBlocked
     *
     * .
     *
     */
    public function testCheckedCommentsForBlocked()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCommentPublic
     *
     * .
     *
     */
    public function testCreateCommentPublic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCommentPublic
     *
     * .
     *
     */
    public function testDeleteCommentPublic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCommentVote
     *
     * .
     *
     */
    public function testDeleteCommentVote()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for flagCommentPublic
     *
     * .
     *
     */
    public function testFlagCommentPublic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCommentText
     *
     * .
     *
     */
    public function testGetCommentText()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCommentVoteUserNames
     *
     * .
     *
     */
    public function testGetCommentVoteUserNames()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCommentsPublic
     *
     * .
     *
     */
    public function testGetCommentsPublic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEventLog
     *
     * .
     *
     */
    public function testGetEventLog()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getGlobalEventLog
     *
     * .
     *
     */
    public function testGetGlobalEventLog()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserNotificationCount
     *
     * .
     *
     */
    public function testGetUserNotificationCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserNotifications
     *
     * .
     *
     */
    public function testGetUserNotifications()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserPresenceStatuses
     *
     * .
     *
     */
    public function testGetUserPresenceStatuses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for lockComment
     *
     * .
     *
     */
    public function testLockComment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pinComment
     *
     * .
     *
     */
    public function testPinComment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resetUserNotificationCount
     *
     * .
     *
     */
    public function testResetUserNotificationCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resetUserNotifications
     *
     * .
     *
     */
    public function testResetUserNotifications()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setCommentText
     *
     * .
     *
     */
    public function testSetCommentText()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unBlockComment
     *
     * .
     *
     */
    public function testUnBlockComment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unLockComment
     *
     * .
     *
     */
    public function testUnLockComment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unPinComment
     *
     * .
     *
     */
    public function testUnPinComment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateUserNotificationCommentSubscriptionStatus
     *
     * .
     *
     */
    public function testUpdateUserNotificationCommentSubscriptionStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateUserNotificationPageSubscriptionStatus
     *
     * .
     *
     */
    public function testUpdateUserNotificationPageSubscriptionStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateUserNotificationStatus
     *
     * .
     *
     */
    public function testUpdateUserNotificationStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for voteComment
     *
     * .
     *
     */
    public function testVoteComment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
