<?php
/**
 * APITenantDailyUsage
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FastComments\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FastComments\Client\Model;

use \ArrayAccess;
use \FastComments\Client\ObjectSerializer;

/**
 * APITenantDailyUsage Class Doc Comment
 *
 * @category Class
 * @package  FastComments\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class APITenantDailyUsage implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'APITenantDailyUsage';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'tenant_id' => 'string',
        'year_number' => 'float',
        'month_number' => 'float',
        'day_number' => 'float',
        'comment_fetch_count' => 'float',
        'comment_create_count' => 'float',
        'conversation_create_count' => 'float',
        'vote_count' => 'float',
        'account_created_count' => 'float',
        'user_mention_search' => 'float',
        'hash_tag_search' => 'float',
        'gif_search_trending' => 'float',
        'gif_search' => 'float',
        'api_credits_used' => 'float',
        'created_at' => '\DateTime',
        'billed' => 'bool',
        'ignored' => 'bool',
        'api_error_count' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'tenant_id' => null,
        'year_number' => 'double',
        'month_number' => 'double',
        'day_number' => 'double',
        'comment_fetch_count' => 'double',
        'comment_create_count' => 'double',
        'conversation_create_count' => 'double',
        'vote_count' => 'double',
        'account_created_count' => 'double',
        'user_mention_search' => 'double',
        'hash_tag_search' => 'double',
        'gif_search_trending' => 'double',
        'gif_search' => 'double',
        'api_credits_used' => 'double',
        'created_at' => 'date-time',
        'billed' => null,
        'ignored' => null,
        'api_error_count' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'tenant_id' => false,
        'year_number' => false,
        'month_number' => false,
        'day_number' => false,
        'comment_fetch_count' => false,
        'comment_create_count' => false,
        'conversation_create_count' => false,
        'vote_count' => false,
        'account_created_count' => false,
        'user_mention_search' => false,
        'hash_tag_search' => false,
        'gif_search_trending' => false,
        'gif_search' => false,
        'api_credits_used' => false,
        'created_at' => false,
        'billed' => false,
        'ignored' => false,
        'api_error_count' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'tenant_id' => 'tenantId',
        'year_number' => 'yearNumber',
        'month_number' => 'monthNumber',
        'day_number' => 'dayNumber',
        'comment_fetch_count' => 'commentFetchCount',
        'comment_create_count' => 'commentCreateCount',
        'conversation_create_count' => 'conversationCreateCount',
        'vote_count' => 'voteCount',
        'account_created_count' => 'accountCreatedCount',
        'user_mention_search' => 'userMentionSearch',
        'hash_tag_search' => 'hashTagSearch',
        'gif_search_trending' => 'gifSearchTrending',
        'gif_search' => 'gifSearch',
        'api_credits_used' => 'apiCreditsUsed',
        'created_at' => 'createdAt',
        'billed' => 'billed',
        'ignored' => 'ignored',
        'api_error_count' => 'apiErrorCount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'tenant_id' => 'setTenantId',
        'year_number' => 'setYearNumber',
        'month_number' => 'setMonthNumber',
        'day_number' => 'setDayNumber',
        'comment_fetch_count' => 'setCommentFetchCount',
        'comment_create_count' => 'setCommentCreateCount',
        'conversation_create_count' => 'setConversationCreateCount',
        'vote_count' => 'setVoteCount',
        'account_created_count' => 'setAccountCreatedCount',
        'user_mention_search' => 'setUserMentionSearch',
        'hash_tag_search' => 'setHashTagSearch',
        'gif_search_trending' => 'setGifSearchTrending',
        'gif_search' => 'setGifSearch',
        'api_credits_used' => 'setApiCreditsUsed',
        'created_at' => 'setCreatedAt',
        'billed' => 'setBilled',
        'ignored' => 'setIgnored',
        'api_error_count' => 'setApiErrorCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'tenant_id' => 'getTenantId',
        'year_number' => 'getYearNumber',
        'month_number' => 'getMonthNumber',
        'day_number' => 'getDayNumber',
        'comment_fetch_count' => 'getCommentFetchCount',
        'comment_create_count' => 'getCommentCreateCount',
        'conversation_create_count' => 'getConversationCreateCount',
        'vote_count' => 'getVoteCount',
        'account_created_count' => 'getAccountCreatedCount',
        'user_mention_search' => 'getUserMentionSearch',
        'hash_tag_search' => 'getHashTagSearch',
        'gif_search_trending' => 'getGifSearchTrending',
        'gif_search' => 'getGifSearch',
        'api_credits_used' => 'getApiCreditsUsed',
        'created_at' => 'getCreatedAt',
        'billed' => 'getBilled',
        'ignored' => 'getIgnored',
        'api_error_count' => 'getApiErrorCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('year_number', $data ?? [], null);
        $this->setIfExists('month_number', $data ?? [], null);
        $this->setIfExists('day_number', $data ?? [], null);
        $this->setIfExists('comment_fetch_count', $data ?? [], null);
        $this->setIfExists('comment_create_count', $data ?? [], null);
        $this->setIfExists('conversation_create_count', $data ?? [], null);
        $this->setIfExists('vote_count', $data ?? [], null);
        $this->setIfExists('account_created_count', $data ?? [], null);
        $this->setIfExists('user_mention_search', $data ?? [], null);
        $this->setIfExists('hash_tag_search', $data ?? [], null);
        $this->setIfExists('gif_search_trending', $data ?? [], null);
        $this->setIfExists('gif_search', $data ?? [], null);
        $this->setIfExists('api_credits_used', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('billed', $data ?? [], null);
        $this->setIfExists('ignored', $data ?? [], null);
        $this->setIfExists('api_error_count', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['tenant_id'] === null) {
            $invalidProperties[] = "'tenant_id' can't be null";
        }
        if ($this->container['year_number'] === null) {
            $invalidProperties[] = "'year_number' can't be null";
        }
        if ($this->container['month_number'] === null) {
            $invalidProperties[] = "'month_number' can't be null";
        }
        if ($this->container['day_number'] === null) {
            $invalidProperties[] = "'day_number' can't be null";
        }
        if ($this->container['comment_fetch_count'] === null) {
            $invalidProperties[] = "'comment_fetch_count' can't be null";
        }
        if ($this->container['comment_create_count'] === null) {
            $invalidProperties[] = "'comment_create_count' can't be null";
        }
        if ($this->container['conversation_create_count'] === null) {
            $invalidProperties[] = "'conversation_create_count' can't be null";
        }
        if ($this->container['vote_count'] === null) {
            $invalidProperties[] = "'vote_count' can't be null";
        }
        if ($this->container['account_created_count'] === null) {
            $invalidProperties[] = "'account_created_count' can't be null";
        }
        if ($this->container['user_mention_search'] === null) {
            $invalidProperties[] = "'user_mention_search' can't be null";
        }
        if ($this->container['hash_tag_search'] === null) {
            $invalidProperties[] = "'hash_tag_search' can't be null";
        }
        if ($this->container['gif_search_trending'] === null) {
            $invalidProperties[] = "'gif_search_trending' can't be null";
        }
        if ($this->container['gif_search'] === null) {
            $invalidProperties[] = "'gif_search' can't be null";
        }
        if ($this->container['api_credits_used'] === null) {
            $invalidProperties[] = "'api_credits_used' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['billed'] === null) {
            $invalidProperties[] = "'billed' can't be null";
        }
        if ($this->container['ignored'] === null) {
            $invalidProperties[] = "'ignored' can't be null";
        }
        if ($this->container['api_error_count'] === null) {
            $invalidProperties[] = "'api_error_count' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return string
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param string $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets year_number
     *
     * @return float
     */
    public function getYearNumber()
    {
        return $this->container['year_number'];
    }

    /**
     * Sets year_number
     *
     * @param float $year_number year_number
     *
     * @return self
     */
    public function setYearNumber($year_number)
    {
        if (is_null($year_number)) {
            throw new \InvalidArgumentException('non-nullable year_number cannot be null');
        }
        $this->container['year_number'] = $year_number;

        return $this;
    }

    /**
     * Gets month_number
     *
     * @return float
     */
    public function getMonthNumber()
    {
        return $this->container['month_number'];
    }

    /**
     * Sets month_number
     *
     * @param float $month_number month_number
     *
     * @return self
     */
    public function setMonthNumber($month_number)
    {
        if (is_null($month_number)) {
            throw new \InvalidArgumentException('non-nullable month_number cannot be null');
        }
        $this->container['month_number'] = $month_number;

        return $this;
    }

    /**
     * Gets day_number
     *
     * @return float
     */
    public function getDayNumber()
    {
        return $this->container['day_number'];
    }

    /**
     * Sets day_number
     *
     * @param float $day_number day_number
     *
     * @return self
     */
    public function setDayNumber($day_number)
    {
        if (is_null($day_number)) {
            throw new \InvalidArgumentException('non-nullable day_number cannot be null');
        }
        $this->container['day_number'] = $day_number;

        return $this;
    }

    /**
     * Gets comment_fetch_count
     *
     * @return float
     */
    public function getCommentFetchCount()
    {
        return $this->container['comment_fetch_count'];
    }

    /**
     * Sets comment_fetch_count
     *
     * @param float $comment_fetch_count comment_fetch_count
     *
     * @return self
     */
    public function setCommentFetchCount($comment_fetch_count)
    {
        if (is_null($comment_fetch_count)) {
            throw new \InvalidArgumentException('non-nullable comment_fetch_count cannot be null');
        }
        $this->container['comment_fetch_count'] = $comment_fetch_count;

        return $this;
    }

    /**
     * Gets comment_create_count
     *
     * @return float
     */
    public function getCommentCreateCount()
    {
        return $this->container['comment_create_count'];
    }

    /**
     * Sets comment_create_count
     *
     * @param float $comment_create_count comment_create_count
     *
     * @return self
     */
    public function setCommentCreateCount($comment_create_count)
    {
        if (is_null($comment_create_count)) {
            throw new \InvalidArgumentException('non-nullable comment_create_count cannot be null');
        }
        $this->container['comment_create_count'] = $comment_create_count;

        return $this;
    }

    /**
     * Gets conversation_create_count
     *
     * @return float
     */
    public function getConversationCreateCount()
    {
        return $this->container['conversation_create_count'];
    }

    /**
     * Sets conversation_create_count
     *
     * @param float $conversation_create_count conversation_create_count
     *
     * @return self
     */
    public function setConversationCreateCount($conversation_create_count)
    {
        if (is_null($conversation_create_count)) {
            throw new \InvalidArgumentException('non-nullable conversation_create_count cannot be null');
        }
        $this->container['conversation_create_count'] = $conversation_create_count;

        return $this;
    }

    /**
     * Gets vote_count
     *
     * @return float
     */
    public function getVoteCount()
    {
        return $this->container['vote_count'];
    }

    /**
     * Sets vote_count
     *
     * @param float $vote_count vote_count
     *
     * @return self
     */
    public function setVoteCount($vote_count)
    {
        if (is_null($vote_count)) {
            throw new \InvalidArgumentException('non-nullable vote_count cannot be null');
        }
        $this->container['vote_count'] = $vote_count;

        return $this;
    }

    /**
     * Gets account_created_count
     *
     * @return float
     */
    public function getAccountCreatedCount()
    {
        return $this->container['account_created_count'];
    }

    /**
     * Sets account_created_count
     *
     * @param float $account_created_count account_created_count
     *
     * @return self
     */
    public function setAccountCreatedCount($account_created_count)
    {
        if (is_null($account_created_count)) {
            throw new \InvalidArgumentException('non-nullable account_created_count cannot be null');
        }
        $this->container['account_created_count'] = $account_created_count;

        return $this;
    }

    /**
     * Gets user_mention_search
     *
     * @return float
     */
    public function getUserMentionSearch()
    {
        return $this->container['user_mention_search'];
    }

    /**
     * Sets user_mention_search
     *
     * @param float $user_mention_search user_mention_search
     *
     * @return self
     */
    public function setUserMentionSearch($user_mention_search)
    {
        if (is_null($user_mention_search)) {
            throw new \InvalidArgumentException('non-nullable user_mention_search cannot be null');
        }
        $this->container['user_mention_search'] = $user_mention_search;

        return $this;
    }

    /**
     * Gets hash_tag_search
     *
     * @return float
     */
    public function getHashTagSearch()
    {
        return $this->container['hash_tag_search'];
    }

    /**
     * Sets hash_tag_search
     *
     * @param float $hash_tag_search hash_tag_search
     *
     * @return self
     */
    public function setHashTagSearch($hash_tag_search)
    {
        if (is_null($hash_tag_search)) {
            throw new \InvalidArgumentException('non-nullable hash_tag_search cannot be null');
        }
        $this->container['hash_tag_search'] = $hash_tag_search;

        return $this;
    }

    /**
     * Gets gif_search_trending
     *
     * @return float
     */
    public function getGifSearchTrending()
    {
        return $this->container['gif_search_trending'];
    }

    /**
     * Sets gif_search_trending
     *
     * @param float $gif_search_trending gif_search_trending
     *
     * @return self
     */
    public function setGifSearchTrending($gif_search_trending)
    {
        if (is_null($gif_search_trending)) {
            throw new \InvalidArgumentException('non-nullable gif_search_trending cannot be null');
        }
        $this->container['gif_search_trending'] = $gif_search_trending;

        return $this;
    }

    /**
     * Gets gif_search
     *
     * @return float
     */
    public function getGifSearch()
    {
        return $this->container['gif_search'];
    }

    /**
     * Sets gif_search
     *
     * @param float $gif_search gif_search
     *
     * @return self
     */
    public function setGifSearch($gif_search)
    {
        if (is_null($gif_search)) {
            throw new \InvalidArgumentException('non-nullable gif_search cannot be null');
        }
        $this->container['gif_search'] = $gif_search;

        return $this;
    }

    /**
     * Gets api_credits_used
     *
     * @return float
     */
    public function getApiCreditsUsed()
    {
        return $this->container['api_credits_used'];
    }

    /**
     * Sets api_credits_used
     *
     * @param float $api_credits_used api_credits_used
     *
     * @return self
     */
    public function setApiCreditsUsed($api_credits_used)
    {
        if (is_null($api_credits_used)) {
            throw new \InvalidArgumentException('non-nullable api_credits_used cannot be null');
        }
        $this->container['api_credits_used'] = $api_credits_used;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets billed
     *
     * @return bool
     */
    public function getBilled()
    {
        return $this->container['billed'];
    }

    /**
     * Sets billed
     *
     * @param bool $billed billed
     *
     * @return self
     */
    public function setBilled($billed)
    {
        if (is_null($billed)) {
            throw new \InvalidArgumentException('non-nullable billed cannot be null');
        }
        $this->container['billed'] = $billed;

        return $this;
    }

    /**
     * Gets ignored
     *
     * @return bool
     */
    public function getIgnored()
    {
        return $this->container['ignored'];
    }

    /**
     * Sets ignored
     *
     * @param bool $ignored ignored
     *
     * @return self
     */
    public function setIgnored($ignored)
    {
        if (is_null($ignored)) {
            throw new \InvalidArgumentException('non-nullable ignored cannot be null');
        }
        $this->container['ignored'] = $ignored;

        return $this;
    }

    /**
     * Gets api_error_count
     *
     * @return float
     */
    public function getApiErrorCount()
    {
        return $this->container['api_error_count'];
    }

    /**
     * Sets api_error_count
     *
     * @param float $api_error_count api_error_count
     *
     * @return self
     */
    public function setApiErrorCount($api_error_count)
    {
        if (is_null($api_error_count)) {
            throw new \InvalidArgumentException('non-nullable api_error_count cannot be null');
        }
        $this->container['api_error_count'] = $api_error_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


