<?php
/**
 * CommentLogType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FastComments\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FastComments\Client\Model;
use \FastComments\Client\ObjectSerializer;

/**
 * CommentLogType Class Doc Comment
 *
 * @category Class
 * @package  FastComments\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CommentLogType
{
    /**
     * Possible values of this enum
     */
    public const NUMBER_0 = 0;

    public const NUMBER_1 = 1;

    public const NUMBER_2 = 2;

    public const NUMBER_3 = 3;

    public const NUMBER_4 = 4;

    public const NUMBER_5 = 5;

    public const NUMBER_6 = 6;

    public const NUMBER_7 = 7;

    public const NUMBER_8 = 8;

    public const NUMBER_9 = 9;

    public const NUMBER_10 = 10;

    public const NUMBER_11 = 11;

    public const NUMBER_12 = 12;

    public const NUMBER_13 = 13;

    public const NUMBER_14 = 14;

    public const NUMBER_15 = 15;

    public const NUMBER_16 = 16;

    public const NUMBER_17 = 17;

    public const NUMBER_18 = 18;

    public const NUMBER_19 = 19;

    public const NUMBER_20 = 20;

    public const NUMBER_21 = 21;

    public const NUMBER_22 = 22;

    public const NUMBER_23 = 23;

    public const NUMBER_24 = 24;

    public const NUMBER_25 = 25;

    public const NUMBER_26 = 26;

    public const NUMBER_27 = 27;

    public const NUMBER_28 = 28;

    public const NUMBER_29 = 29;

    public const NUMBER_30 = 30;

    public const NUMBER_31 = 31;

    public const NUMBER_32 = 32;

    public const NUMBER_33 = 33;

    public const NUMBER_34 = 34;

    public const NUMBER_35 = 35;

    public const NUMBER_36 = 36;

    public const NUMBER_37 = 37;

    public const NUMBER_38 = 38;

    public const NUMBER_39 = 39;

    public const NUMBER_40 = 40;

    public const NUMBER_41 = 41;

    public const NUMBER_42 = 42;

    public const NUMBER_43 = 43;

    public const NUMBER_44 = 44;

    public const NUMBER_45 = 45;

    public const NUMBER_46 = 46;

    public const NUMBER_47 = 47;

    public const NUMBER_48 = 48;

    public const NUMBER_49 = 49;

    public const NUMBER_50 = 50;

    public const NUMBER_51 = 51;

    public const NUMBER_52 = 52;

    public const NUMBER_53 = 53;

    public const NUMBER_54 = 54;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NUMBER_0,
            self::NUMBER_1,
            self::NUMBER_2,
            self::NUMBER_3,
            self::NUMBER_4,
            self::NUMBER_5,
            self::NUMBER_6,
            self::NUMBER_7,
            self::NUMBER_8,
            self::NUMBER_9,
            self::NUMBER_10,
            self::NUMBER_11,
            self::NUMBER_12,
            self::NUMBER_13,
            self::NUMBER_14,
            self::NUMBER_15,
            self::NUMBER_16,
            self::NUMBER_17,
            self::NUMBER_18,
            self::NUMBER_19,
            self::NUMBER_20,
            self::NUMBER_21,
            self::NUMBER_22,
            self::NUMBER_23,
            self::NUMBER_24,
            self::NUMBER_25,
            self::NUMBER_26,
            self::NUMBER_27,
            self::NUMBER_28,
            self::NUMBER_29,
            self::NUMBER_30,
            self::NUMBER_31,
            self::NUMBER_32,
            self::NUMBER_33,
            self::NUMBER_34,
            self::NUMBER_35,
            self::NUMBER_36,
            self::NUMBER_37,
            self::NUMBER_38,
            self::NUMBER_39,
            self::NUMBER_40,
            self::NUMBER_41,
            self::NUMBER_42,
            self::NUMBER_43,
            self::NUMBER_44,
            self::NUMBER_45,
            self::NUMBER_46,
            self::NUMBER_47,
            self::NUMBER_48,
            self::NUMBER_49,
            self::NUMBER_50,
            self::NUMBER_51,
            self::NUMBER_52,
            self::NUMBER_53,
            self::NUMBER_54
        ];
    }
}


