<?php
/**
 * ModerationFilter
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FastComments\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * fastcomments
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FastComments\Client\Model;

use \ArrayAccess;
use \FastComments\Client\ObjectSerializer;

/**
 * ModerationFilter Class Doc Comment
 *
 * @category Class
 * @package  FastComments\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModerationFilter implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ModerationFilter';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'reviewed' => 'bool',
        'approved' => 'bool',
        'is_spam' => 'bool',
        'is_banned_user' => 'bool',
        'is_locked' => 'bool',
        'flag_count_gt' => 'float',
        'user_id' => 'string',
        'url_id' => 'string',
        'domain' => 'string',
        'moderation_group_ids' => 'string[]',
        'comment_text_search' => 'string[]',
        'exact_comment_text' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'reviewed' => null,
        'approved' => null,
        'is_spam' => null,
        'is_banned_user' => null,
        'is_locked' => null,
        'flag_count_gt' => 'double',
        'user_id' => null,
        'url_id' => null,
        'domain' => null,
        'moderation_group_ids' => null,
        'comment_text_search' => null,
        'exact_comment_text' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'reviewed' => false,
        'approved' => false,
        'is_spam' => false,
        'is_banned_user' => false,
        'is_locked' => false,
        'flag_count_gt' => false,
        'user_id' => false,
        'url_id' => false,
        'domain' => false,
        'moderation_group_ids' => false,
        'comment_text_search' => false,
        'exact_comment_text' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'reviewed' => 'reviewed',
        'approved' => 'approved',
        'is_spam' => 'isSpam',
        'is_banned_user' => 'isBannedUser',
        'is_locked' => 'isLocked',
        'flag_count_gt' => 'flagCountGt',
        'user_id' => 'userId',
        'url_id' => 'urlId',
        'domain' => 'domain',
        'moderation_group_ids' => 'moderationGroupIds',
        'comment_text_search' => 'commentTextSearch',
        'exact_comment_text' => 'exactCommentText'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'reviewed' => 'setReviewed',
        'approved' => 'setApproved',
        'is_spam' => 'setIsSpam',
        'is_banned_user' => 'setIsBannedUser',
        'is_locked' => 'setIsLocked',
        'flag_count_gt' => 'setFlagCountGt',
        'user_id' => 'setUserId',
        'url_id' => 'setUrlId',
        'domain' => 'setDomain',
        'moderation_group_ids' => 'setModerationGroupIds',
        'comment_text_search' => 'setCommentTextSearch',
        'exact_comment_text' => 'setExactCommentText'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'reviewed' => 'getReviewed',
        'approved' => 'getApproved',
        'is_spam' => 'getIsSpam',
        'is_banned_user' => 'getIsBannedUser',
        'is_locked' => 'getIsLocked',
        'flag_count_gt' => 'getFlagCountGt',
        'user_id' => 'getUserId',
        'url_id' => 'getUrlId',
        'domain' => 'getDomain',
        'moderation_group_ids' => 'getModerationGroupIds',
        'comment_text_search' => 'getCommentTextSearch',
        'exact_comment_text' => 'getExactCommentText'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('reviewed', $data ?? [], null);
        $this->setIfExists('approved', $data ?? [], null);
        $this->setIfExists('is_spam', $data ?? [], null);
        $this->setIfExists('is_banned_user', $data ?? [], null);
        $this->setIfExists('is_locked', $data ?? [], null);
        $this->setIfExists('flag_count_gt', $data ?? [], null);
        $this->setIfExists('user_id', $data ?? [], null);
        $this->setIfExists('url_id', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('moderation_group_ids', $data ?? [], null);
        $this->setIfExists('comment_text_search', $data ?? [], null);
        $this->setIfExists('exact_comment_text', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets reviewed
     *
     * @return bool|null
     */
    public function getReviewed()
    {
        return $this->container['reviewed'];
    }

    /**
     * Sets reviewed
     *
     * @param bool|null $reviewed reviewed
     *
     * @return self
     */
    public function setReviewed($reviewed)
    {
        if (is_null($reviewed)) {
            throw new \InvalidArgumentException('non-nullable reviewed cannot be null');
        }
        $this->container['reviewed'] = $reviewed;

        return $this;
    }

    /**
     * Gets approved
     *
     * @return bool|null
     */
    public function getApproved()
    {
        return $this->container['approved'];
    }

    /**
     * Sets approved
     *
     * @param bool|null $approved approved
     *
     * @return self
     */
    public function setApproved($approved)
    {
        if (is_null($approved)) {
            throw new \InvalidArgumentException('non-nullable approved cannot be null');
        }
        $this->container['approved'] = $approved;

        return $this;
    }

    /**
     * Gets is_spam
     *
     * @return bool|null
     */
    public function getIsSpam()
    {
        return $this->container['is_spam'];
    }

    /**
     * Sets is_spam
     *
     * @param bool|null $is_spam is_spam
     *
     * @return self
     */
    public function setIsSpam($is_spam)
    {
        if (is_null($is_spam)) {
            throw new \InvalidArgumentException('non-nullable is_spam cannot be null');
        }
        $this->container['is_spam'] = $is_spam;

        return $this;
    }

    /**
     * Gets is_banned_user
     *
     * @return bool|null
     */
    public function getIsBannedUser()
    {
        return $this->container['is_banned_user'];
    }

    /**
     * Sets is_banned_user
     *
     * @param bool|null $is_banned_user is_banned_user
     *
     * @return self
     */
    public function setIsBannedUser($is_banned_user)
    {
        if (is_null($is_banned_user)) {
            throw new \InvalidArgumentException('non-nullable is_banned_user cannot be null');
        }
        $this->container['is_banned_user'] = $is_banned_user;

        return $this;
    }

    /**
     * Gets is_locked
     *
     * @return bool|null
     */
    public function getIsLocked()
    {
        return $this->container['is_locked'];
    }

    /**
     * Sets is_locked
     *
     * @param bool|null $is_locked is_locked
     *
     * @return self
     */
    public function setIsLocked($is_locked)
    {
        if (is_null($is_locked)) {
            throw new \InvalidArgumentException('non-nullable is_locked cannot be null');
        }
        $this->container['is_locked'] = $is_locked;

        return $this;
    }

    /**
     * Gets flag_count_gt
     *
     * @return float|null
     */
    public function getFlagCountGt()
    {
        return $this->container['flag_count_gt'];
    }

    /**
     * Sets flag_count_gt
     *
     * @param float|null $flag_count_gt flag_count_gt
     *
     * @return self
     */
    public function setFlagCountGt($flag_count_gt)
    {
        if (is_null($flag_count_gt)) {
            throw new \InvalidArgumentException('non-nullable flag_count_gt cannot be null');
        }
        $this->container['flag_count_gt'] = $flag_count_gt;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string|null
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string|null $user_id user_id
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        if (is_null($user_id)) {
            throw new \InvalidArgumentException('non-nullable user_id cannot be null');
        }
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets url_id
     *
     * @return string|null
     */
    public function getUrlId()
    {
        return $this->container['url_id'];
    }

    /**
     * Sets url_id
     *
     * @param string|null $url_id url_id
     *
     * @return self
     */
    public function setUrlId($url_id)
    {
        if (is_null($url_id)) {
            throw new \InvalidArgumentException('non-nullable url_id cannot be null');
        }
        $this->container['url_id'] = $url_id;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string|null
     */
    public function getDomain()
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string|null $domain domain
     *
     * @return self
     */
    public function setDomain($domain)
    {
        if (is_null($domain)) {
            throw new \InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets moderation_group_ids
     *
     * @return string[]|null
     */
    public function getModerationGroupIds()
    {
        return $this->container['moderation_group_ids'];
    }

    /**
     * Sets moderation_group_ids
     *
     * @param string[]|null $moderation_group_ids moderation_group_ids
     *
     * @return self
     */
    public function setModerationGroupIds($moderation_group_ids)
    {
        if (is_null($moderation_group_ids)) {
            throw new \InvalidArgumentException('non-nullable moderation_group_ids cannot be null');
        }
        $this->container['moderation_group_ids'] = $moderation_group_ids;

        return $this;
    }

    /**
     * Gets comment_text_search
     *
     * @return string[]|null
     */
    public function getCommentTextSearch()
    {
        return $this->container['comment_text_search'];
    }

    /**
     * Sets comment_text_search
     *
     * @param string[]|null $comment_text_search Text search terms. Each term is matched case-insensitively against the comment text. A term wrapped in quotes means exact phrase match.
     *
     * @return self
     */
    public function setCommentTextSearch($comment_text_search)
    {
        if (is_null($comment_text_search)) {
            throw new \InvalidArgumentException('non-nullable comment_text_search cannot be null');
        }
        $this->container['comment_text_search'] = $comment_text_search;

        return $this;
    }

    /**
     * Gets exact_comment_text
     *
     * @return string|null
     */
    public function getExactCommentText()
    {
        return $this->container['exact_comment_text'];
    }

    /**
     * Sets exact_comment_text
     *
     * @param string|null $exact_comment_text Set by the `exact=\"...\"` search syntax. The comment text must equal this value exactly (case-sensitive, full-string), as opposed to the substring matching of commentTextSearch.
     *
     * @return self
     */
    public function setExactCommentText($exact_comment_text)
    {
        if (is_null($exact_comment_text)) {
            throw new \InvalidArgumentException('non-nullable exact_comment_text cannot be null');
        }
        $this->container['exact_comment_text'] = $exact_comment_text;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


